---
title: "Welcome"
pagetitle: "Aakash Basnet"
page-layout: full
toc: false
css: core/assets/css/index.css
listing:
    - id: services-listing
      contents: core/solutions
      type: grid
      sort: title
      fields: [image,title, subtitle, description, ]
      image-height: 200px 
      max-description-length: 400
      grid-columns: 3
    - id: testimonial-listing
      contents: core/testimonials
      type: grid
      sort: title
      fields: [image,title, subtitle, description, ]
      image-height: 50px 
      max-description-length: 400
      grid-columns: 3

    
---
::: {.hero-banner}
# Freelancer , with 6 years of experiences
### I specialize in Python automation, data engineering, and developing impactful web applications and dashboards. Let's collaborate to enhance your operational efficiency and unlock the potential of data-driven insights.
:::

<button class="btn-action-primary"> Contact Me </button>
<button class="btn-action-primary"> Learn More</button>
<br>

# Services


Embark on a transformative journey with my freelance services in IT and Finance Solutions. With over 6 years of experience, I specialize in Python automation, data engineering, and crafting impactful web applications and dashboards. As a seasoned freelancer, I bring a holistic approach to addressing complex challenges. My proficiency extends to designing robust ETL pipelines and implementing machine learning and AI tools to keep you at the forefront of technological innovation. Explore my portfolio for successful projects, and let's collaborate to enhance your operational efficiency and unlock the potential of data-driven insights. Contact me today to discuss how we can tailor these advanced solutions to meet your unique business needs
<br>
<br>

::: {.card-grid}
::: {#services-listing}
:::
:::


<br>

# Testimonials 
These are the testimonials from the awesome peoples that i have worked in the past.

<br>
<br>

::: {.testimonials-grid}
::: {#testimonial-listing}
:::
:::

<!-- C.alendly badge widget begin -->
<link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">
<script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript" async></script>
<script type="text/javascript">window.onload = function() { Calendly.initBadgeWidget({ url: 'https://calendly.com/basnetaakash17/30min', text: 'Schedule time with Aakash', color: '#0069ff', textColor: '#ffffff', branding: false }); }</script>
<!-- Calendly badge widget end -->