---
title: "Contact"

# Form extension from: https://github.com/jlgraves-ubc/forms/blob/main/example.qmd
form:
  id: contact-me-form
  submit: "Submit"
  action: "javascript:submit()"
  fields:
  - name: email
    type: text
    id: textid
    label: "Email *"
    required: true
  - name: subject
    type: text
    id: textid2
    label: "Subject *"
    required: true
  - name: message
    id: textarea1
    type: textarea
    label: "Message *"
    required: true
    width: 30 #in rows
    height: 30 #in cols
---


Thank you for your interest in reaching out to me. 

Whether you have queries, require consulting services, or are seeking solutions, I'm here to help. Your questions matter, and I'd love to receive your message.I am committed to providing prompt and personalized responses to address your specific needs.

You can use the contact form below to get in touch, or if you prefer,
<a href="" onclick="Calendly.initPopupWidget({url: 'https://calendly.com/basnetaakash17/30min'});return false;">schedule a meeting </a>
  at your convenience. 



{{<form>}}


<!-- Calendly badge widget begin -->
<link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">
<script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript" async></script>
<script type="text/javascript">window.onload = function() { Calendly.initBadgeWidget({ url: 'https://calendly.com/basnetaakash17/30min', text: 'Schedule time with Aakash', color: '#0069ff', textColor: '#ffffff', branding: false }); }</script>
<!-- Calendly badge widget end -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

<script>
    function submit () {
      form = document.querySelector("#form")
      form_data = new FormData(form)
      console.log(form_data)
      console.log("Test contact")
      // TODO create a datetime today
      // TODO need to save this on google sheets
    }
</script>